### ISSUE TITLE
Media import puts files in wrong folder

### ISSUE THREAD

**Issue by thecontrarycat** [KevinJump/uSync#13]
# Importing Media from usync\data\media
Assume you have a media item that has an umbracoFile property with a value of "/media/1084/image.png" and an associated _usyncMedia folder containing image.png.

## On the first pass:
- The media item is created
- The file is uploaded to the media item
- The media item is saved
- The umbracoFile property is set to the new path that Umbraco has uploaded it to (on a brand new Umbraco, this may be /media/1001/image.png - certainly it will be different from the value in umbracoFile).

## On the second pass:
- All properties from the media.config are imported onto the media item
- OOPS!  Your media item now has an umbracoFile property with the value "/media/1084/image.png" (from the xml) and now no longer points to the image on disk.

# Side-effects
Because the umbracoFile property is not loaded prior to moving the image, every full import always uploads every file _to new folders_ resulting in duplicate, orphaned media items and an ever-growing media folder.

# Suggested fix
- Either change DeserializeCore in MediaSerializer.cs to set the properties prior to importing the file (in which case it will always end up in the same media folder on each Umbraco instance - possibly causing collisions for an import into an existing instance)

- OR, change DesearlizeSecondPass in MediaSerializer.cs to strip the umbracoFile, umbracoExtension, umbracoHeight, umbracoWidth and umbracoBytes properties from the node before sending to ContentBaseSerializer.DeserializeMappedIds

- OR, change ContentBaseSerializer.DeserializeMappedIds to ignore all umbraco* media properties (possibly extend to have a configurable ignoredProperties list?)

**Comment by KevinJump** [comment]
doh, I think i've also slightly complicated it by adding the  `<MoveMedia>true</MoveMedia>` option which doesn't do the media file import but lets you copy the media folder over thus preserving the umbracoFile from the source site is preferable. 

Option 1 is almost what the MoveMedia Option does - but you have to copy the media folder. (see https://github.com/KevinJump/uSync/issues/9#issuecomment-165082547 for details)

I think I  'just' need to move the call to `ImportFile(attempt.Item, mediaFolder)` which is the thing that actually does the file bit in https://github.com/KevinJump/uSync/blob/master/Jumoo.uSync.Content/MediaHandler.cs#L46 into the second pass

**Comment by thecontrarycat** [comment]
Confirmed that moving ImportFile to the second pass fixes my issue

**Comment by KevinJump** [comment]
yeah. - Will roll this up into the next release.
