### ISSUE TITLE
MultiNodeTreePicker StartNode is not getting set correctly

### ISSUE THREAD

**Issue by thecontrarycat** [KevinJump/uSync#14]
# Importing DataTypes from usync/data/DataType
Assume you have a DataType that represents a MultiNodeTreePicker set to pick a particular document type beneath a particular start node in the content tree:
```
<?xml version="1.0" encoding="utf-8"?>
<DataType Name="App Picker" Key="285b4e36-ad32-46ac-9866-1992af9d28ca" Id="Umbraco.MultiNodeTreePicker" DatabaseType="Nvarchar">
  <Nodes>
    <Node Id="1073" Value="Catalogue\Apps" Type="content" MapGuid="1" />
  </Nodes>
  <PreValues>
    <PreValue Id="58" Value="{&#xD;&#xA;  &quot;type&quot;: &quot;content&quot;,&#xD;&#xA;  &quot;id&quot;: 1073&#xD;&#xA;}" Alias="startNode" MapGuid="1" />
    <PreValue Id="59" Value="App" Alias="filter" />
    <PreValue Id="60" Value="1" Alias="minNumber" />
    <PreValue Id="61" Value="" Alias="maxNumber" />
    <PreValue Id="62" Value="0" Alias="showEditButton" />
  </PreValues>
</DataType>
```

Note that MapGuid="1" is correctly set on the PreValue containing the id of the startNode.

## When Importing:
- DataTypes are imported *before* Content (by necessity as the properties on the content need to exist!)
- When in DeserializeGetMappedValues the mapper is correctly loaded (i.e. it thinks it understands MNTPs)
- When in MapToId it tries to look up the correct Id for the content node (in GetMappedId), however... if the content has not been imported yet the uSyncTreeWalker will return -1 and the importer will treat this as if the original Id is correct.

## The Issue
If importing content into a new Umbraco instance we can't guarantee that NodeIds will be the same so we cannot use the Id in the startNode xml (it needs to be mapped).  However, if we try to create the DataType before we have created the Content then mapping will fail (as content doesn't exist).  If we instead try to create the Content before the DataType it will fail (as the property can't be created as no DataType).

## Potential Solutions
DataTypes should be parsed in two phases:
1. Create the DataType and basic parameters (Name, Type, DatabaseType)
2. After Content has been imported, return to the DataTypes and complete the process by importing the PreValues.

**Comment by KevinJump** [comment]
yeah DataTypes should have a second import, this is how usync 2.x does it. but v3 loads handlers with priorities and then runs them through in that order. 

I either need to make all the second pass imports happen after all the first pass ones (this might work, but introduces the risk of partial failure leaving a lot of things half set), or get a way of the DataTypeHandler registering itself twice .
