### ISSUE TITLE
Deleted content item throws error on Import

### ISSUE THREAD

**Issue by heilc** [KevinJump/uSync#18]
In my Umbraco 7.3.0 site I am getting an error when I delete an item from the content tree (moves into recycle bin) and do a full import.

The error:
Cannot insert duplicate key row in object 'dbo.umbracoNode' with unique index 'IX_umbracoNode_uniqueID'. The duplicate key value is {guid}.
The statement has been terminated.

The nuget packages I have installed are 
-uSunc v3.0.3
-uSync.Core v5.1.0
-uSync.BackOffice v3.0.3
-uSync.ContentEdition v3.0.0

Steps to reproduce:
1. Delete data folder on disk
2. In backoffice, use the usync panel to export (creating new data folder)
3. In content tree, delete an item
4. Use usync panel to perform a full import

**Comment by KevinJump** [comment]
yep, uSync wasn't coping with the trashed content nodes properly.

adding support - if the imported node is found in the trash then the content is untrashed and all the properties are set on import (if we do this we keep the internal GUIDs of the content so all the mapping can still work)

will be in next release.

**Comment by KevinJump** [comment]
Fixed in latest release batch (content v3.0.1) (released now)
