### ISSUE TITLE
Content Import Regression

### ISSUE THREAD

**Issue by thecontrarycat** [KevinJump/uSync#3]
Since the refactor in f5e24d9a57bafda9778528fa1abfd9a01653dde5 the ability to import content with a prevalue datatype has regressed.

It appears that the mapping code is only running when importing DataTypes and not when importing the content itself.  Note that the export works correctly.

For example, a DropDownList datatype with options { Alias | Name } { 0 | Option 0 }, { 1 | Option 1 }, { 2 | Option 2}.  If the content has selected Option 0 it correctly writes the alias of 0 in the .config file.  However, on import it is supposed to look up the PreValue and store the Id of the prevalue in the property.  Instead, it is simply storing 0 in the property value (and therefore not mapping to the correct prevalue).

**Comment by KevinJump** [comment]
HI I need to get my head around this. 

A normal `Umbraco.Dropdown`. stores the value in the content, so if we have a list with  

 ```xml
<PreValues>
    <PreValue Id="6" Value="First" Alias="0" />
    <PreValue Id="7" Value="Second" Alias="1" />
    <PreValue Id="8" Value="Third" Alias="2" />
  </PreValues>
```
then the content config might store... 
```xml
<dropdownpicked><![CDATA[Third]]></dropdownpicked>
```

with this it doesn't matter about mapping IDs because the list is storing the value not the id?

however a list of `Umbraco.DropdownlistPublishingKeys` does store the id, so when i have a list of 

```xml
    <PreValue Id="12" Value="Thing" Alias="0" />
    <PreValue Id="13" Value="Totherthing" Alias="1" />
```
the content might store. 
```xml
<tother>13</tother>
```
but we want it to store ?
```xml
  <tother>Totherthing</tother>
```

and then at the other end map totherthing back to an ID that might not be 13?

I think this is it, does that make sense to you?

**Comment by thecontrarycat** [comment]
Ah, I see the confusion.

With the DropDownList and RadioButtonList datatypes there are several different fields we might use as a value.

`Id` is the *primary key* in the `cmsDataTypePreValue` table - this is an identity and will usually be different on different systems
`Value` is the textual representation that is shown in the content editor
`Alias` is a *secondary id* for that datatype only and so can be kept in sync across multiple systems.  (It is a likely guess that this was introduced for exactly this purpose with Courier)

The annoying thing is that the actual value stored in `cmsPropertyData` is the `Id` (i.e. the one thing that isn't portable).  Therefore, when we export we should convert the `Id` to the `Alias` and store that in our XML.  On import, we need to recognise that we are importing into a suitable DataType and convert that `alias` back into the local system's `Id` value.  Note that the textual representation is not used at all for these data types.

uSync RC3 currently does the export correctly, but the import is no longer mapping back from `alias` to `id`.  The code submission I sent earlier did do this step so you should be able to get the code from that.

**Comment by thecontrarycat** [comment]
I just did a test with Umbraco.DropdownlistPublishingKeys and the behaviour seems to be the same as Umbraco.DropdownList.

I wonder if this is a change somewhere along the way and it used to store the Value instead of the Id?

Either way, this is the behaviour I'm seeing in 7.2.8 and 7.3.0 RC and as uSync 3 depends upon 7.3+ we should be able to assume that this will be the behaviour from now on.

**Comment by KevinJump** [comment]
Ah, 
I hadn't noticed the change in how the Alias was being stored, previously the alias was auto incrementing on these types. 

makes sense now :smile:

**Comment by KevinJump** [comment]
Right, i think i've gotten this now, 

I have split the mappers off into a Mappers folder, so this can be made a bit more flexible if we need to map more things, 

so now we have:

- A Datatype mapper, that takes values, and turns them into aliases.
- A DataTypeKey mapper that takes internal ids and turns them into alias.
- the contentMapper that does the content ids inside text and the like.

I've made the mappers also support comma separated values, as then we get checkbox lists, dropdown multiples and radiolists for free. 

see commit:  2c41983a574fb5a330a73ec1427b7fd3f39e3b90

The usynccore.config has changes too as the type of mapping are now all in there.

**Comment by thecontrarycat** [comment]
Confirmed as fixed

**Comment by KevinJump** [comment]
:tada:
