### ISSUE TITLE
After delete of content Node, Umbraco throws Exception

### ISSUE THREAD

**Issue by gmanrodt** [KevinJump/uSync#7]
If you delete a content node from Umbraco (v7.3), then restart Umbraco (by modifying the web.config), on reload of the Umbraco backoffice or Front Office, we receive an exception which states: "Cannot insert duplicate key row in object 'dbo.umbracoNode' with unique index 'IX_umbracoNode_uniqueID'. "

This seems to be caused by uSync (ContentEdition v3.0.0) trying to insert the content node even though I deleted it. Since the content node is still in the database, but is marked as "trashed". 

The way to fix this is to delete the folder in uSync\data\content that matches the content node I deleted.

**Comment by KevinJump** [comment]
yeah. 

uSync should delete the file when you delete the content node (doh!) 

looks like there is also a situation where a save can be fired on the trashed item, which gets it written back to the usync folder. 

Fixes in [192701c527cc5a9d81c97d66c5b584ec55d25671] are
* make sure we delete the right file on trashed (path was wrong)
* only save non-trashed items to disk on save. 

I'll push out a new uSync.Content Package once i've done all the checks.

**Comment by KevinJump** [comment]
Will be in next release (being built today)
